version: "2"
services:
  tucluster:
    build: .
    user: wwwuser
    volumes:
     - .:/tucluster
    environment:
    - TUCLUSTER_CONFIG=tucluster_docker.json
    - CELERY_CONFIG_MODULE=docker_celeryconfig
    - PYTHONPATH=/tucluster
    depends_on:
      - mongo
      - redis
    links:
      - mongo
      - redis
    ports:
      - "8000:8000"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  mongo:
      image: mongo:latest
      ports:
          - "27017:27017"
      command: mongod

  qflow:
    image: qflow
    user: wwwuser
    depends_on:
      - redis
    links:
      - redis
    volumes:
     - .:/tucluster
    environment:
      - CELERY_CONFIG_MODULE=docker_celeryconfig
      - PYTHONPATH=/tucluster
